=== ShantanuDas8013/Web_Dev/XML/Ecommerce.dtd
<!ENTITY category1 "Clothing">
<!ENTITY category2 "Accessories">
<!ENTITY category3 "Home Decor">
<!ENTITY product1 "Custom T-Shirt">
<!ENTITY product2 "Personalized Mug">
<!ENTITY product3 "Engraved Keychain">
<!ENTITY product4 "Custom Pillow">
<!ENTITY product5 "Monogrammed Tote Bag">
<!ENTITY option1 "Size: S, M, L, XL">
<!ENTITY option2 "Color: Red, Blue, Green">
<!ENTITY option3 "Material: Cotton, Polyester">

<!ELEMENT Ecommerce (Product+)>
<!ELEMENT Product (Name, Category, Price, Customization)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Category (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ELEMENT Customization (Option+)>
<!ELEMENT Option (#PCDATA)>

=== ShantanuDas8013/Web_Dev/XML/Ecommerce.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Ecommerce.xsl"?>
<!DOCTYPE Ecommerce SYSTEM "Ecommerce.dtd">
<Ecommerce>
    <Product>
        <Name>Custom T-Shirt</Name>
        <Category>Clothing</Category>
        <Price>19.99</Price>
        <Customization>
            <Option>Size: S, M, L, XL</Option>
            <Option>Color: Red, Blue, Green</Option>
        </Customization>
    </Product>
    <Product>
        <Name>Personalized Mug</Name>
        <Category>Clothing</Category>
        <Price>12.50</Price>
        <Customization>
            <Option>Color: Red, Blue, Green</Option>
        </Customization>
    </Product>
    <Product>
        <Name>Engraved Keychain</Name>
        <Category>Accessories</Category>
        <Price>15.00</Price>
        <Customization>
            <Option>Size: S, M, L, XL</Option>
            <Option>Material: Cotton, Polyester</Option>
        </Customization>
    </Product>
    <Product>
        <Name>Custom Pillow</Name>
        <Category>Home Decor</Category>
        <Price>25.00</Price>
        <Customization>
            <Option>Size: S, M, L, XL</Option>
        </Customization>
    </Product>
    <Product>
        <Name>Monogrammed Tote Bag</Name>
        <Category>Clothing</Category>
        <Price>30.00</Price>
        <Customization>
            <Option>Color: Red, Blue, Green</Option>
            <Option>Material: Cotton, Polyester</Option>
        </Customization>
    </Product>
</Ecommerce>
